FROM openjdk:21-slim
EXPOSE 8085
ARG JAR_FILE=./consumer2.jar
ENV DB_URL=jdbc:mysql://mysql:3306/kafka_bd
ENV DB_USERNAME=admin
ENV DB_PASSWORD=12345
COPY ${JAR_FILE} app.jar
ENTRYPOINT [ "java", "-jar", "app.jar", "--DB_URL=jdbc:mysql://mysql:3306/kafka_bd", "--DB_USERNAME=admin", "--DB_PASSWORD=12345" ]
#ENTRYPOINT [ "java", "-jar", "app.jar", "--DB_URL=${DB_URL}", "--DB_USERNAME=${DB_USERNAME}", "--DB_PASSWORD=${DB_PASSWORD}" ]